// <auto-generated />
using System;
using EntregaFacil.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntregaFacil.Api.Migrations
{
    [DbContext(typeof(EntregaFacilDbContext))]
    partial class EntregaFacilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EntregaFacil.Api.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "12.345.678/0001-90",
                            Name = "FastLog Express",
                            Phone = "(11) 3000-1000"
                        },
                        new
                        {
                            Id = 2,
                            Cnpj = "98.765.432/0001-10",
                            Name = "Entrega Sul",
                            Phone = "(41) 3000-2000"
                        });
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.DeliveryOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliveryOccurrences");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.DeliveryReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("DeliveryReviews");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "ana.souza@example.com",
                            CustomerName = "Ana Souza",
                            Number = "ORD-1001",
                            OrderDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "AwaitingSeparation",
                            TotalAmount = 339.80m
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "bruno.lima@example.com",
                            CustomerName = "Bruno Lima",
                            Number = "ORD-1002",
                            OrderDate = new DateTime(2026, 5, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "AwaitingSeparation",
                            TotalAmount = 159.90m
                        });
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 89.90m,
                            UnitPrice = 89.90m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            TotalPrice = 249.90m,
                            UnitPrice = 249.90m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            TotalPrice = 159.90m,
                            UnitPrice = 159.90m
                        });
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRD-001",
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 89.90m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Code = "PRD-002",
                            Description = "Compact mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 249.90m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 3,
                            Code = "PRD-003",
                            Description = "Hub with HDMI and USB ports",
                            Name = "USB-C Hub",
                            Price = 159.90m,
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarrierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.DeliveryOccurrence", b =>
                {
                    b.HasOne("EntregaFacil.Api.Models.Order", "Order")
                        .WithMany("DeliveryOccurrences")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.DeliveryReview", b =>
                {
                    b.HasOne("EntregaFacil.Api.Models.Order", "Order")
                        .WithOne("DeliveryReview")
                        .HasForeignKey("EntregaFacil.Api.Models.DeliveryReview", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.OrderItem", b =>
                {
                    b.HasOne("EntregaFacil.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregaFacil.Api.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Shipment", b =>
                {
                    b.HasOne("EntregaFacil.Api.Models.Carrier", "Carrier")
                        .WithMany("Shipments")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntregaFacil.Api.Models.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("EntregaFacil.Api.Models.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Carrier", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Order", b =>
                {
                    b.Navigation("DeliveryOccurrences");

                    b.Navigation("DeliveryReview");

                    b.Navigation("Items");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("EntregaFacil.Api.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
